### ISSUE TITLE
Heating State

### ISSUE THREAD

**Issue by faxbio** [muchasuerte/home-assistant#6]
Hi there,
not an issue, more like a PR...
I used to create a sensor tracking while the boiler flame is burning, since the climate component changed your code  i'm not able to do that again.

I suppose that:
self._heating_state = data.get('heating', '') == '1'

store the information but i cannot find it in the exported properties. There's a way to access this information in HA or do i need some code change in your component?

**Comment by muchasuerte** [comment]
By default the climate use the hvac_action which could have these values:
- off
- cooling
- heating

on last commit I made a change to include the heating_state attribute which is boolean, now can be true or false.

I have also removed the target temperature which was not ok to be integrated with other services like google nest hub.
